//
//  PokeAnnotation.swift
//  PokeMap
//
//  Created by Danny Luong on 7/25/17.
//  Copyright © 2017 dnylng. All rights reserved.
//

import Foundation
import MapKit

let pokemon = ["Bulbasaur",
               "Ivysaur",
               "Venusaur",
               "Charmander",
               "Charmeleon",
               "Charizard",
               "Squirtle",
               "Wartortle",
               "Blastoise",
               "Caterpie",
               "Metapod",
               "Butterfree",
               "Weedle",
               "Kakuna",
               "Beedrill",
               "Pidgey",
               "Pidgeotto",
               "Pidgeot",
               "Rattata",
               "Raticate",
               "Spearow",
               "Fearow",
               "Ekans",
               "Arbok",
               "Pikachu",
               "Raichu",
               "Sandshrew",
               "Sandslash",
               "Nidoran",
               "Nidorina",
               "Nidoqueen",
               "Nidoran",
               "Nidorino",
               "Nidoking",
               "Clefairy",
               "Clefable",
               "Vulpix",
               "Ninetales",
               "Jigglypuff",
               "Wigglytuff",
               "Zubat",
               "Golbat",
               "Oddish",
               "Gloom",
               "Vileplume",
               "Paras",
               "Parasect",
               "Venonat",
               "Venomoth",
               "Diglett",
               "Dugtrio",
               "Meowth",
               "Persian",
               "Psyduck",
               "Golduck",
               "Mankey",
               "Primeape",
               "Growlithe",
               "Arcanine",
               "Poliwag",
               "Poliwhirl",
               "Poliwrath",
               "Abra",
               "Kadabra",
               "Alakazam",
               "Machop",
               "Machoke",
               "Machamp",
               "Bellsprout",
               "Weepinbell",
               "Victreebel",
               "Tentacool",
               "Tentacruel",
               "Geodude",
               "Graveler",
               "Golem",
               "Ponyta",
               "Rapidash",
               "Slowpoke",
               "Slowbro",
               "Magnemite",
               "Magneton",
               "Farfetch'd",
               "Doduo",
               "Dodrio",
               "Seel",
               "Dewgong",
               "Grimer",
               "Muk",
               "Shellder",
               "Cloyster",
               "Gastly",
               "Haunter",
               "Gengar",
               "Onix",
               "Drowzee",
               "Hypno",
               "Krabby",
               "Kingler",
               "Voltorb",
               "Electrode",
               "Exeggcute",
               "Exeggutor",
               "Cubone",
               "Marowak",
               "Hitmonlee",
               "Hitmonchan",
               "Lickitung",
               "Koffing",
               "Weezing",
               "Rhyhorn",
               "Rhydon",
               "Chansey",
               "Tangela",
               "Kangaskhan",
               "Horsea",
               "Seadra",
               "Goldeen",
               "Seaking",
               "Staryu",
               "Starmie",
               "Mr. Mime",
               "Scyther",
               "Jynx",
               "Electabuzz",
               "Magmar",
               "Pinsir",
               "Tauros",
               "Magikarp",
               "Gyarados",
               "Lapras",
               "Ditto",
               "Eevee",
               "Vaporeon",
               "Jolteon",
               "Flareon",
               "Porygon",
               "Omanyte",
               "Omastar",
               "Kabuto",
               "Kabutops",
               "Aerodactyl",
               "Snorlax",
               "Articuno",
               "Zapdos",
               "Moltres",
               "Dratini",
               "Dragonair",
               "Dragonite",
               "Mewtwo",
               "Mew"]

class PokeAnnotation: NSObject, MKAnnotation {
    var coordinate = CLLocationCoordinate2D()
    var pokeId: Int
    var pokeName: String
    var title: String?
    
    init(coordinate: CLLocationCoordinate2D, pokeId: Int) {
        self.coordinate = coordinate
        self.pokeId = pokeId
        self.pokeName = pokemon[pokeId - 1].capitalized
        self.title = self.pokeName
    }
}
